DROP SCHEMA IF EXISTS EMS CASCADE;
CREATE SCHEMA IF NOT EXISTS EMS AUTHORIZATION sa;
CREATE TABLE IF NOT EXISTS EMS.EMPLOYEES
(
    ID                     VARCHAR2(36) NOT NULL,
    FIRST_NAME             VARCHAR2(36) NOT NULL,
    LAST_NAME              VARCHAR2(36) NOT NULL,
    EMAIL                  VARCHAR2(36) NOT NULL
);